### ISSUE TITLE
NoMethodError in Spree::Admin::Orders#index for Russian locale

### ISSUE THREAD

**Issue by Kapranov** [spree-contrib/spree_static_content#193] opened 2015-05-25 18:25 UTC
When we have russian locale We got error
NoMethodError in Spree::Admin::Orders#index
undefined method `%' for :many:Symbol

**Comment by devsli** [comment] 2015-07-02 05:52
Duplicate of #192

**Comment by futhr** [comment] 2015-10-05 11:23
@Kapranov dup, issue resolved with cbeaceb1e799568572855777c8b406e900abf571 for `3-0-stable` branch.

**Closed by futhr** 2015-10-05 11:23 UTC
